name: "ROS Build"
description: "Build ROS packages and generate debian packages using rosdep and bloom"
inputs:
  PROJECT_NAME:
    description: "Project name"
    required: true
runs:
  using: "composite"
  steps:
    - name: rosdep
      run: |
        export ROSDISTRO_INDEX_URL=file://`pwd`/index-v4.yaml \
        && export ROS_DISTRO=humble \
        && echo "yaml file://`pwd`/rosdep/base.yaml" > /etc/ros/rosdep/sources.list.d/20-default.list \
        && echo "yaml file://`pwd`/rosdep/python.yaml" >> /etc/ros/rosdep/sources.list.d/20-default.list \
        && echo "yaml file://`pwd`/rosdep/custom_rosdep.yaml" > /etc/ros/rosdep/sources.list.d/30-custom.list \
        && rosdep update --rosdistro humble
      shell: bash
    - name: colcon
      run: | 
        colcon build --packages-up-to ${{ inputs.PROJECT_NAME }}
      shell: bash
    - name: bloom
      run: | 
        export ROSDISTRO_INDEX_URL=file://`pwd`/index-v4.yaml \
        && source /opt/ros/humble/setup.bash \
        && source install/setup.bash \
        && cd src/${{ inputs.PROJECT_NAME }} \
        && bloom-generate rosdebian 
      shell: bash
    - name: fakeroot
      run: |
        source install/setup.bash \
        && cd src/${{ inputs.PROJECT_NAME }} \
        && fakeroot debian/rules binary
      shell: bash