name: My Action
on: [workflow_dispatch]
jobs:



  build_pkg_interface:
    runs-on: arm
    steps:
      - name: clean
        run: |
          rm -rf src/pkg_interface/debian \
          && rm -rf src/pkg_interface/.obj-*-linux-gnu
      - name: bloom
        run: | 
          source /opt/ros/humble/setup.bash \
          && cd src/pkg_interface \
          && bloom-generate rosdebian 
      - name: fakeroot
        run: |
          cd src/pkg_interface \
          && fakeroot debian/rules binary

  build_pkg_server:
    runs-on: arm
    steps:
      - name: rosdep
        run: |
          export ROSDISTRO_INDEX_URL=file://`pwd`/index-v4.yaml \
          && export ROS_DISTRO=humble \
          && echo "yaml file://`pwd`/rosdep/base.yaml" > /etc/ros/rosdep/sources.list.d/20-default.list \
          && echo "yaml file://`pwd`/rosdep/python.yaml" >> /etc/ros/rosdep/sources.list.d/20-default.list \
          && echo "yaml file://`pwd`/rosdep/custom_rosdep.yaml" > /etc/ros/rosdep/sources.list.d/30-custom.list \
          && rosdep update --rosdistro humble
      - name: bloom
        run: | 
          export ROSDISTRO_INDEX_URL=file://`pwd`/index-v4.yaml
          source /opt/ros/humble/setup.bash \
          && cd src/pkg_server \
          && bloom-generate rosdebian 
      - name: fakeroot
        run: |
          cd src/pkg_server \
          && fakeroot debian/rules binary

  build_pkg_client:
    runs-on: arm
    steps:
      - name: clean
        run: |
          rm -rf src/pkg_client/debian \
          && rm -rf src/pkg_client/.obj-*-linux-gnu
      - name: rosdep
        run: |
          export ROS_DISTRO=humble \
          && echo "yaml file://`pwd`/rosdep/custom_rosdep.yaml" > /etc/ros/rosdep/sources.list.d/30-custom.list \
          && cat /etc/ros/rosdep/sources.list.d/30-custom.list \
          && rosdep update --rosdistro humble
      - name: bloom
        run: source /opt/ros/humble/setup.bash && cd src/pkg_client && bloom-generate rosdebian 
      - name: fakeroot
        run: |
          cd src/pkg_client \
          && fakeroot debian/rules binary

  build_pc_pkg_interface_ng:
    runs-on: pc
    steps:
      - name: build
        uses: ./.github/actions/ros_build
        with:
          PROJECT_NAME: pkg_interface



  build_pc_pkg_interface:
    runs-on: pc
    env:
      PROJECT_NAME: pkg_interface
    steps:
      - name: rosdep
        run: |
          export ROSDISTRO_INDEX_URL=file://`pwd`/index-v4.yaml \
          && export ROS_DISTRO=humble \
          && echo "yaml file://`pwd`/rosdep/base.yaml" > /etc/ros/rosdep/sources.list.d/20-default.list \
          && echo "yaml file://`pwd`/rosdep/python.yaml" >> /etc/ros/rosdep/sources.list.d/20-default.list \
          && echo "yaml file://`pwd`/rosdep/custom_rosdep.yaml" > /etc/ros/rosdep/sources.list.d/30-custom.list \
          && rosdep update --rosdistro humble
      - name: colcon
        run: | 
          colcon build --packages-up-to $PROJECT_NAME 
      - name: bloom
        run: | 
          export ROSDISTRO_INDEX_URL=file://`pwd`/index-v4.yaml \
          && source /opt/ros/humble/setup.bash \
          && source install/setup.bash \
          && cd src/$PROJECT_NAME \
          && bloom-generate rosdebian 
      - name: fakeroot
        run: |
          source install/setup.bash \
          && cd src/$PROJECT_NAME \
          && fakeroot debian/rules binary